// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "dynamic-pricing/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PriceRepository is an autogenerated mock type for the PriceRepository type
type PriceRepository struct {
	mock.Mock
}

type PriceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PriceRepository) EXPECT() *PriceRepository_Expecter {
	return &PriceRepository_Expecter{mock: &_m.Mock}
}

// GetPrice provides a mock function with given fields: ctx, productID
func (_m *PriceRepository) GetPrice(ctx context.Context, productID uuid.UUID) (models.Price, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetPrice")
	}

	var r0 models.Price
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.Price, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.Price); ok {
		r0 = rf(ctx, productID)
	} else {
		r0 = ret.Get(0).(models.Price)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PriceRepository_GetPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrice'
type PriceRepository_GetPrice_Call struct {
	*mock.Call
}

// GetPrice is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
func (_e *PriceRepository_Expecter) GetPrice(ctx interface{}, productID interface{}) *PriceRepository_GetPrice_Call {
	return &PriceRepository_GetPrice_Call{Call: _e.mock.On("GetPrice", ctx, productID)}
}

func (_c *PriceRepository_GetPrice_Call) Run(run func(ctx context.Context, productID uuid.UUID)) *PriceRepository_GetPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PriceRepository_GetPrice_Call) Return(_a0 models.Price, _a1 error) *PriceRepository_GetPrice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PriceRepository_GetPrice_Call) RunAndReturn(run func(context.Context, uuid.UUID) (models.Price, error)) *PriceRepository_GetPrice_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertPrice provides a mock function with given fields: ctx, productID, currentPrice
func (_m *PriceRepository) UpsertPrice(ctx context.Context, productID uuid.UUID, currentPrice float64) (models.Price, error) {
	ret := _m.Called(ctx, productID, currentPrice)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPrice")
	}

	var r0 models.Price
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, float64) (models.Price, error)); ok {
		return rf(ctx, productID, currentPrice)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, float64) models.Price); ok {
		r0 = rf(ctx, productID, currentPrice)
	} else {
		r0 = ret.Get(0).(models.Price)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, float64) error); ok {
		r1 = rf(ctx, productID, currentPrice)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PriceRepository_UpsertPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertPrice'
type PriceRepository_UpsertPrice_Call struct {
	*mock.Call
}

// UpsertPrice is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
//   - currentPrice float64
func (_e *PriceRepository_Expecter) UpsertPrice(ctx interface{}, productID interface{}, currentPrice interface{}) *PriceRepository_UpsertPrice_Call {
	return &PriceRepository_UpsertPrice_Call{Call: _e.mock.On("UpsertPrice", ctx, productID, currentPrice)}
}

func (_c *PriceRepository_UpsertPrice_Call) Run(run func(ctx context.Context, productID uuid.UUID, currentPrice float64)) *PriceRepository_UpsertPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(float64))
	})
	return _c
}

func (_c *PriceRepository_UpsertPrice_Call) Return(_a0 models.Price, _a1 error) *PriceRepository_UpsertPrice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PriceRepository_UpsertPrice_Call) RunAndReturn(run func(context.Context, uuid.UUID, float64) (models.Price, error)) *PriceRepository_UpsertPrice_Call {
	_c.Call.Return(run)
	return _c
}

// NewPriceRepository creates a new instance of PriceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPriceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PriceRepository {
	mock := &PriceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
