FROM golang:1.23 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/catalog ./cmd/app/catalog

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=build /out/catalog /catalog
COPY config.yaml /config.yaml
USER nonroot:nonroot
ENV CONFIG_PATH=/config.yaml
ENTRYPOINT ["/catalog"]
