// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// EventBus is an autogenerated mock type for the EventBus type
type EventBus struct {
	mock.Mock
}

type EventBus_Expecter struct {
	mock *mock.Mock
}

func (_m *EventBus) EXPECT() *EventBus_Expecter {
	return &EventBus_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: ctx, key, value
func (_m *EventBus) Send(ctx context.Context, key string, value []byte) error {
	ret := _m.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventBus_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type EventBus_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value []byte
func (_e *EventBus_Expecter) Send(ctx interface{}, key interface{}, value interface{}) *EventBus_Send_Call {
	return &EventBus_Send_Call{Call: _e.mock.On("Send", ctx, key, value)}
}

func (_c *EventBus_Send_Call) Run(run func(ctx context.Context, key string, value []byte)) *EventBus_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *EventBus_Send_Call) Return(_a0 error) *EventBus_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventBus_Send_Call) RunAndReturn(run func(context.Context, string, []byte) error) *EventBus_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewEventBus creates a new instance of EventBus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventBus(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventBus {
	mock := &EventBus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
